version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0970asdF%
      MYSQL_DATABASE: devinit
      MYSQL_USER: bussayamas
      MYSQL_PASSWORD: banana
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - db:db